// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACm_UftIeHDPPtIJjprPBYERZcx6ErWFc',
    appId: '1:648792069849:web:734a72dccb6af9bed710c8',
    messagingSenderId: '648792069849',
    projectId: 'ekik-b52fa',
    authDomain: 'ekik-b52fa.firebaseapp.com',
    storageBucket: 'ekik-b52fa.firebasestorage.app',
    measurementId: 'G-Q88RQ3TNH7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKNTm7IDI75dLibmLdXDcOtDPh446w4OI',
    appId: '1:648792069849:android:38c1cd008e8b4313d710c8',
    messagingSenderId: '648792069849',
    projectId: 'ekik-b52fa',
    storageBucket: 'ekik-b52fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU4m4Ky-AZ9eVwMqyZJffZot3nai2b5MQ',
    appId: '1:648792069849:ios:b3b3c7a2d0ac8a94d710c8',
    messagingSenderId: '648792069849',
    projectId: 'ekik-b52fa',
    storageBucket: 'ekik-b52fa.firebasestorage.app',
    androidClientId: '648792069849-gn2jfn8kqqe441joa7d2fpav8poching.apps.googleusercontent.com',
    iosClientId: '648792069849-kk1jg11tvf9o6dgf7mo6gauqbklgp4j7.apps.googleusercontent.com',
    iosBundleId: 'com.example.exploreFlutter2',
  );

}